version: "3.7"
services:
  portainer:
    image: portainer/portainer
    restart: always
    expose:
      - 9000
    environment:
      - VIRTUAL_HOST={HOSTNAME}
    networks:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/portainer/data:/data

networks:
  nginx-proxy:
